CREATE SCHEMA E_LOCAL

CREATE DOMAIN email AS VARCHAR(40);
CREATE DOMAIN password AS VARCHAR(15);
CREATE EXTENSION "uuid-ossp";

CREATE TABLE USUARIO (
  ID_Usuario CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  Email email UNIQUE,
  Password password NOT NULL,
  Nome VARCHAR(20) NOT NULL,
  Sobrenome VARCHAR(30) NOT NULL,
  Telefone CHAR(11),
  Imagem_Usuario BYTEA,
  PRIMARY KEY (ID_Usuario)
);

CREATE TABLE LOJA (
  ID_Loja CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  Password password NOT NULL,
  Email email UNIQUE,
  Nome VARCHAR(20) NOT NULL,
  Telefone CHAR(11),
  Imagem_Loja BYTEA,
  Nome_Proprietario VARCHAR(20) NOT NULL,
  Sobrenome_Proprietario VARCHAR(30) NOT NULL,
  Email_Proprietario email NOT NULL,
  Telefone_Proprietario CHAR(11) NOT NULL,
  PRIMARY KEY (ID_Loja)
);

CREATE TABLE ENTREGADOR (
  ID_Entregador CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  Email email UNIQUE,
  Password password NOT NULL,
  Nome VARCHAR(20) NOT NULL,
  Sobrenome VARCHAR(30) NOT NULL,
  Telefone CHAR(11) NOT NULL,
  Imagem_Entregador BYTEA,
  PRIMARY KEY (ID_Entregador)
);

CREATE TABLE TIPO_ENDERECO (
  ID_Tipo_Endereco VARCHAR(5),
  Descricao VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID_Tipo_Endereco)
);

CREATE TABLE METODOS_DE_PAGAMENTO (
  ID_Metodo VARCHAR(5),
  Descricao VARCHAR(10) NOT NULL,
  PRIMARY KEY (ID_Metodo)
);

CREATE TABLE PEDIDO_STATUS_CODE (
  ID_Pedido_Status_code VARCHAR(5),
  Descricao VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID_Pedido_Status_code)
);

CREATE TABLE METODO_DE_ENTREGA (
  ID_Metodo_Entrega VARCHAR(5),
  Descricao VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID_Metodo_Entrega)
);

CREATE TABLE FATURA_STATUS_CODE (
  ID_Fatura_Status_code VARCHAR(5),
  Descricao VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID_Fatura_Status_code)
);

CREATE TABLE TIPO_PRODUTO (
  ID_Tipo_Produto VARCHAR(5),
  Descricao VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID_Tipo_Produto)
);

CREATE TABLE PEDIDO_ITENS_STATUS_CODE (
  ID_PI_Status_code VARCHAR(5),
  Descricao VARCHAR(25) NOT NULL,
  PRIMARY KEY (ID_PI_Status_code)
);

CREATE TABLE TRANSPORTE_STATUS_CODE (
  ID_Transporte_Status_code VARCHAR(5),
  Descricao VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID_Transporte_Status_code)
);

CREATE TABLE TIPO_ENDERECO (
  ID_Tipo_Endereco VARCHAR(5),
  Descricao VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID_Tipo_Endereco)
);

CREATE TABLE ENDERECO (
  ID_Endereco CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  CEP CHAR(8) NOT NULL,
  Pais VARCHAR(20) NOT NULL,
  Estado VARCHAR(20) NOT NULL
  Cidade VARCHAR(20) NOT NULL,
  Bairro VARCHAR(50) NOT NULL,
  Rua VARCHAR(50) NOT NULL,
  Numero INT DEFAULT 0,
  Complemento VARCHAR(50),
  PRIMARY KEY (ID_Endereco)
);

CREATE TABLE LOJAS_ENDERECO (
  ID_LJ_Endereco CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Loja CHAR(20) DEFAULT CURRENT_USER,
  ID_Tipo_Endereco VARCHAR(5),
  ID_Endereco CHAR(20),
  PRIMARY KEY (ID_LJ_Endereco),
  FOREIGN KEY (ID_Loja) REFERENCES LOJA(ID_Loja)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Endereco) REFERENCES ENDERECO(ID_Endereco)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Tipo_Endereco)
	REFERENCES TIPO_ENDERECO(ID_Tipo_Endereco)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE USUARIOS_ENDERECO (
  ID_US_Endereco CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Usuario CHAR(20) DEFAULT CURRENT_USER,
  ID_Tipo_Endereco VARCHAR(5),
  ID_Endereco CHAR(20),
  PRIMARY KEY (ID_US_Endereco),
  FOREIGN KEY (ID_Usuario) REFERENCES USUARIO(ID_Usuario)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Endereco) REFERENCES ENDERECO(ID_Endereco)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Tipo_Endereco)
	REFERENCES TIPO_ENDERECO(ID_Tipo_Endereco)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ENTREGADORES_ENDERECO (
  ID_ET_Endereco CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Entregador CHAR(20) DEFAULT CURRENT_USER,
  ID_Tipo_Endereco VARCHAR(5),
  ID_Endereco CHAR(20),
  PRIMARY KEY (ID_ET_Endereco),
  FOREIGN KEY (ID_Entregador)
	REFERENCES ENTREGADOR(ID_Entregador)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Endereco) REFERENCES ENDERECO(ID_Endereco)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Tipo_Endereco)
	REFERENCES TIPO_ENDERECO(ID_Tipo_Endereco)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE BUSCA (
  ID_Busca CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Usuario CHAR(20),
  Descricao VARCHAR(20),
  PRIMARY KEY (ID_Busca),
  FOREIGN KEY (ID_Usuario) REFERENCES USUARIO(ID_Usuario)
	ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE CARTAO (
  ID_Cartao CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Metodo VARCHAR(5),
  ID_Usuario CHAR(20) DEFAULT CURRENT_USER,
  Nome VARCHAR(20) NOT NULL,
  Numero CHAR(20) NOT NULL,
  Validade DATE NOT NULL,
  CVC CHAR(3) NOT NULL,
  PRIMARY KEY (ID_Cartao),
  FOREIGN KEY (ID_Usuario) REFERENCES USUARIO (ID_Usuario)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Metodo)
	REFERENCES METODOS_DE_PAGAMENTO(ID_Metodo)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE PEDIDO (
  ID_Pedido CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Usuario CHAR(20) DEFAULT CURRENT_USER,
  ID_Pedido_Status_code VARCHAR(5),
  ID_Metodo_Entrega VARCHAR(5),
  Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_Pedido),
  FOREIGN KEY (ID_Usuario) REFERENCES USUARIO(ID_Usuario)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Pedido_Status_code)
	REFERENCES PEDIDO_STATUS_CODE(ID_Pedido_Status_code)
	ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (ID_Metodo_Entrega)
	REFERENCES METODO_DE_ENTREGA(ID_Metodo_Entrega)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE FATURA (
  ID_Fatura CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Pedido CHAR(20),
  ID_Fatura_Status_code VARCHAR(5),
  Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_Fatura),
  FOREIGN KEY (ID_Pedido) REFERENCES PEDIDO(ID_Pedido)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Fatura_Status_code)
	REFERENCES FATURA_STATUS_CODE(ID_Fatura_Status_code)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE PAGAMENTO (
  ID_Pagamento CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Fatura CHAR(20),
  ID_Cartao CHAR(20),
  Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Valor DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (ID_Pagamento),
  FOREIGN KEY (ID_Fatura) REFERENCES FATURA(ID_Fatura)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Cartao) REFERENCES CARTAO(ID_Cartao)
	ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE PRODUTO (
  ID_Produto CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Loja CHAR(20) DEFAULT CURRENT_USER,
  ID_Tipo_Produto VARCHAR(5),
  Nome VARCHAR(20) NOT NULL,
  Valor DOUBLE PRECISION NOT NULL,
  Descricao VARCHAR(120),
  Imagem_Produto BYTEA,
  PRIMARY KEY (ID_Produto),
  FOREIGN KEY (ID_Loja) REFERENCES LOJA(ID_Loja)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Tipo_Produto)
	REFERENCES TIPO_PRODUTO(ID_Tipo_Produto)
	ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE PEDIDO_ITENS (
  ID_Pedido_Itens CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Pedido CHAR(20),
  ID_Produto CHAR(20),
  ID_PI_Status_code VARCHAR(5),
  PRIMARY KEY (ID_Pedido_Itens),
  FOREIGN KEY (ID_Pedido) REFERENCES PEDIDO(ID_Pedido)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Produto) REFERENCES PRODUTO (ID_Produto)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_PI_Status_code)
	REFERENCES PEDIDO_ITENS_STATUS_CODE(ID_PI_Status_code)
	ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE TRANSPORTE (
  ID_Transporte CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Pedido CHAR(20),
  ID_Transporte_Status_code VARCHAR(5),
  Data_Entrega TIMESTAMP,
  PRIMARY KEY (ID_Transporte),
  FOREIGN KEY (ID_Transporte_Status_code)
	REFERENCES TRANSPORTE_STATUS_CODE(ID_Transporte_Status_code)
	ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE TRANSPORTE_DELIVERY (
  ID_T_Delivery CHAR(20) DEFAULT UUID_GENERATE_V4()::CHAR(20),
  ID_Transporte CHAR(20),
  ID_Entregador CHAR(20),
  ID_US_Endereco CHAR(20),
  Data_saida TIMESTAMP,
  PRIMARY KEY (ID_T_Delivery),
  FOREIGN KEY (ID_US_Endereco)
	REFERENCES USUARIOS_ENDERECO(ID_US_Endereco)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Entregador) REFERENCES ENTREGADOR(ID_Entregador)
	ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_Transporte) REFERENCES TRANSPORTE(ID_Transporte)
	ON DELETE SET NULL ON UPDATE CASCADE
);
